void connect_jid(void **state);
void connect_jid_requests_roster(void **state);
void connect_jid_sends_presence_after_receiving_roster(void **state);
void connect_jid_requests_bookmarks(void **state);
void connect_bad_password(void **state);
void show_presence_updates(void **state);
//void sends_rooms_iq(void **state);
//void multiple_pings(void **state);
//void responds_to_ping(void **state);
