.TH man 1 "2025-03-27" "0.15.0" "Profanity XMPP client"

.SH NAME
/ban

.SH DESCRIPTION
Ban user from chat room.

.SH SYNOPSIS
/ban <jid> [<reason>]

.LP

.SH ARGUMENTS
.PP
\fB<jid>\fR
.RS 4
Bare JID of the user to ban from the room.
.RE
.PP
\fB<reason>\fR
.RS 4
Optional reason for banning the user.
.RE
