.TH man 1 "2025-03-27" "0.15.0" "Profanity XMPP client"

.SH NAME
/avatar

.SH DESCRIPTION
Upload an avatar for yourself, disable your avatar, or download a contact's avatar (XEP-0084). If nothing happens after using this command, the user either doesn't have an avatar set or doesn't use XEP-0084 to publish it.

.SH SYNOPSIS
/avatar set <path>

.LP
/avatar disable

.LP
/avatar get <barejid>

.LP
/avatar open <barejid>

.LP

.SH ARGUMENTS
.PP
\fBset <path>\fR
.RS 4
Set avatar to the image at <path>.
.RE
.PP
\fBdisable\fR
.RS 4
Disable avatar publishing; your avatar will not display to others.
.RE
.PP
\fBget <barejid>\fR
.RS 4
Download the avatar. barejid is the JID to download avatar from.
.RE
.PP
\fBopen <barejid>\fR
.RS 4
Download avatar and open it with command. See /executable.
.RE

.SH EXAMPLES
/avatar set ~/images/avatar.png

.LP
/avatar disable

.LP
/avatar get thor@valhalla.edda

.LP
/avatar open freyja@vanaheimr.edda

.LP
