.TH man 1 "2026-02-23" "0.16.0" "Profanity XMPP client"

.SH NAME
/beep

.SH DESCRIPTION
Switch the terminal bell on or off. The bell will sound when incoming messages are received. If the terminal does not support sounds, it may attempt to flash the screen instead.

.SH SYNOPSIS
/beep on|off

.LP

.SH ARGUMENTS
.PP
\fBon|off\fR
.RS 4
Enable or disable terminal bell.
.RE
