.TH Profanity 1 "January 2017" "Profanity XMPP client"
.SH NAME
Profanity \- a simple console based XMPP chat client.
.SH SYNOPSIS
.B profanity
[\-vh] [\-l level] [\-a account]
.SH DESCRIPTION
.B Profanity
is a simple lightweight console based XMPP chat client. Its emphasis is 
on having a simple and configurable command driven UI, see the homepage
at:
.br
.PP
<http://www.profanity.im>
.SH OPTIONS
.TP
.BI "\-v, \-\-version"
Show version and build information.
.TP
.BI "\-h, \-\-help"
Show help on command line arguments.
.TP
.BI "\-a, \-\-account "ACCOUNT
Auto connect to an account on startup,
.I ACCOUNT
must be an existing account.
.TP
.BI "\-l, \-\-log "LEVEL
Set the logging level,
.I LEVEL
may be set to DEBUG, INFO (the default), WARN or ERROR.
.SH USING PROFANITY
The user guide can be found at <http://www.profanity.im/userguide.html>.
.SH SEE ALSO
.B Profanity
itself has a lot of built\-in help. Check the /help command for more information.
Type "/help help" for information on how to use help itself.
.SH CONFIGURATION
Configuration for
.B Profanity
is stored in
.I $XDG_CONFIG_HOME/profanity/profrc
, details on commands for configuring Profanity can be found at <http://www.profanity.im/reference.html>.
.PP
.SH BUGS
Bugs can either be reported by raising an issue at the Github issue tracker:
.br
.PP
<https://github.com/boothj5/profanity/issues>
.br
.PP
or to the mailing list at:
.br
.PP
<https://groups.google.com/forum/#!forum/profanitydev>
.br
.PP
or by sending a mail directly to:
.br
.PP
<boothj5web@gmail.com>
.br
.PP
.SH LICENSE
Copyright (C) 2012 \- 2017 James Booth <boothj5web@gmail.com>.
License GPLv3+: GNU GPL version 3 or later <https://www.gnu.org/licenses/gpl.html>
This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
.SH AUTHORS/CREDITS
.B Profanity
was written by James Booth
.B <boothj5web@gmail.com>
with many contributions from others, see the full list at: <https://github.com/boothj5/profanity/graphs/contributors>
