.TH man 1 "2021-09-28" "0.11.0" "Profanity XMPP client"

.SH NAME
/gone

.SH DESCRIPTION
Send a 'gone' state to the recipient after the specified number of minutes. Chat states (/states) will be enabled if this setting is set.

.SH SYNOPSIS
/gone <minutes>

.LP

.SH ARGUMENTS
.PP
\fB<minutes>\fR
.RS 4
Number of minutes of inactivity before sending the 'gone' state, a value of 0 will disable sending this state.
.RE
