.TH man 1 "2022-09-13" "0.13.0" "Profanity XMPP client"

.SH NAME
/intype

.SH DESCRIPTION
Show when a contact is typing in the console, and in active message window.

.SH SYNOPSIS
/intype console|titlebar on|off

.LP

.SH ARGUMENTS
.PP
\fBtitlebar on|off\fR
.RS 4
Enable or disable contact typing messages notification in titlebar.
.RE
.PP
\fBconsole on|off\fR
.RS 4
Enable or disable contact typing messages notification in console window.
.RE
