.TH man 1 "2022-03-30" "0.12.0" "Profanity XMPP client"

.SH NAME
/plugins

.SH DESCRIPTION
Manage plugins. Passing no arguments lists currently loaded plugins and global plugins which are available for local installation. Global directory for Python plugins is /usr/local/share/profanity/plugins and for C Plugins is /usr/local/lib64/profanity/plugins.

.SH SYNOPSIS
/plugins

.LP
/plugins install [<path>]

.LP
/plugins uninstall [<plugin>]

.LP
/plugins update [<path>]

.LP
/plugins unload [<plugin>]

.LP
/plugins load [<plugin>]

.LP
/plugins reload [<plugin>]

.LP
/plugins python_version

.LP

.SH ARGUMENTS
.PP
\fBinstall [<path>]\fR
.RS 4
Install a plugin, or all plugins found in a directory (recursive). And loads it/them.
.RE
.PP
\fBuninstall [<plugin>]\fR
.RS 4
Uninstall a plugin.
.RE
.PP
\fBupdate [<path>]\fR
.RS 4
Updates an installed plugin
.RE
.PP
\fBload [<plugin>]\fR
.RS 4
Load a plugin that already exists in the plugin directory, passing no argument loads all found plugins. It will be loaded upon next start too unless unloaded.
.RE
.PP
\fBunload [<plugin>]\fR
.RS 4
Unload a loaded plugin, passing no argument will unload all plugins.
.RE
.PP
\fBreload [<plugin>]\fR
.RS 4
Reload a plugin, passing no argument will reload all plugins.
.RE
.PP
\fBpython_version\fR
.RS 4
Show the Python interpreter version.
.RE

.SH EXAMPLES
/plugins install

.LP
/plugins install /home/steveharris/Downloads/metal.py

.LP
/plugins update /home/steveharris/Downloads/metal.py

.LP
/plugins uninstall browser.py

.LP
/plugins load browser.py

.LP
/plugins unload say.py

.LP
/plugins reload wikipedia.py

.LP
