.TH man 1 "2021-09-28" "0.11.0" "Profanity XMPP client"

.SH NAME
/help

.SH DESCRIPTION
Help on using Profanity. Passing no arguments list help areas. For command help, optional arguments are shown using square brackets, arguments representing variables rather than a literal name are surrounded by angle brackets. Arguments that may be one of a number of values are separated by a pipe e.g. val1|val2|val3.

.SH SYNOPSIS
/help [<area>|<command>|search_all|search_any] [<search_terms>]

.LP

.SH ARGUMENTS
.PP
\fB<area>\fR
.RS 4
Summary help for commands in a certain area of functionality.
.RE
.PP
\fB<command>\fR
.RS 4
Full help for a specific command, for example '/help connect'.
.RE
.PP
\fBsearch_all <search_terms>\fR
.RS 4
Search commands for returning matches that contain all of the search terms.
.RE
.PP
\fBsearch_any <search_terms>\fR
.RS 4
Search commands for returning matches that contain any of the search terms.
.RE

.SH EXAMPLES
/help search_all presence online

.LP
/help commands

.LP
/help presence

.LP
/help who

.LP
