.TH man 1 "2021-09-28" "0.11.0" "Profanity XMPP client"

.SH NAME
/reconnect

.SH DESCRIPTION
Set the reconnect attempt interval for when the connection is lost.

.SH SYNOPSIS
/reconnect <seconds>

.LP

.SH ARGUMENTS
.PP
\fB<seconds>\fR
.RS 4
Number of seconds before attempting to reconnect, a value of 0 disables reconnect.
.RE
