.TH man 1 "2025-08-22" "0.15.0" "Profanity XMPP client"

.SH NAME
/room

.SH DESCRIPTION
Chat room configuration.

.SH SYNOPSIS
/room accept|destroy|config

.LP

.SH ARGUMENTS
.PP
\fBaccept\fR
.RS 4
Accept default room configuration.
.RE
.PP
\fBdestroy\fR
.RS 4
Reject default room configuration, and destroy the room.
.RE
.PP
\fBconfig\fR
.RS 4
Edit room configuration.
.RE
