.TH man 1 "2026-02-23" "0.16.0" "Profanity XMPP client"

.SH NAME
/cmd

.SH DESCRIPTION
Execute ad hoc commands.

.SH SYNOPSIS
/cmd list [<jid>]

.LP
/cmd exec <command> [<jid>]

.LP

.SH ARGUMENTS
.PP
\fBlist\fR
.RS 4
List supported ad hoc commands.
.RE
.PP
\fBexec <command>\fR
.RS 4
Execute a command.
.RE

.SH EXAMPLES
/cmd list

.LP
/cmd exec ping

.LP
