.TH man 1 "2021-01-09" "0.10.0" "Profanity XMPP client"

.SH NAME
/wins

.SH DESCRIPTION
Manage windows. Passing no argument will list all currently active windows and information about their usage.

.SH SYNOPSIS
/wins

.LP
/wins unread

.LP
/wins prune

.LP
/wins swap <source> <target>

.LP

.SH ARGUMENTS
.PP
\fBunread\fR
.RS 4
List windows with unread messages.
.RE
.PP
\fBprune\fR
.RS 4
Close all windows with no unread messages.
.RE
.PP
\fBswap <source> <target>\fR
.RS 4
Swap windows, target may be an empty position.
.RE
