.TH man 1 "2022-04-04" "0.12.0" "Profanity XMPP client"

.SH NAME
/kick

.SH DESCRIPTION
Kick occupant from chat room.

.SH SYNOPSIS
/kick <nick> [<reason>]

.LP

.SH ARGUMENTS
.PP
\fB<nick>\fR
.RS 4
Nickname of the occupant to kick from the room.
.RE
.PP
\fB<reason>\fR
.RS 4
Optional reason for kicking the occupant.
.RE
