.TH man 1 "2023-08-03" "0.13.1" "Profanity XMPP client"

.SH NAME
/software

.SH DESCRIPTION
Find out a contact, or room members software version information. If in private chat initiated from a chat room, no parameter is required. If the contact's software does not support software version requests, nothing will be displayed.

.SH SYNOPSIS
/software

.LP
/software <fulljid>|<nick>

.LP

.SH ARGUMENTS
.PP
\fB<fulljid>\fR
.RS 4
If in the console or a chat window, the full JID for which you wish to see software information.
.RE
.PP
\fB<nick>\fR
.RS 4
If in a chat room, nickname for which you wish to see software information.
.RE

.SH EXAMPLES
/software odin@valhalla.edda/laptop

.LP
/software odin@valhalla.edda/phone

.LP
/software thor

.LP
