.TH man 1 "2021-01-09" "0.10.0" "Profanity XMPP client"

.SH NAME
/mainwin

.SH DESCRIPTION
Move the main window.

.SH SYNOPSIS
/mainwin up

.LP
/mainwin down

.LP

.SH ARGUMENTS
.PP
\fBup\fR
.RS 4
Move the main window up the screen.
.RE
.PP
\fBdown\fR
.RS 4
Move the main window down the screen.
.RE
