.TH man 1 "2021-01-09" "0.10.0" "Profanity XMPP client"

.SH NAME
/serversoftware

.SH DESCRIPTION
Find server or component software version information.

.SH SYNOPSIS
/serversoftware <domain>

.LP

.SH ARGUMENTS
.PP
\fB<domain>\fR
.RS 4
The jid of your server or component.
.RE

.SH EXAMPLES
/software valhalla.edda

.LP
/software xmpp.vanaheimr.edda

.LP
