.TH man 1 "2022-10-12" "0.13.0" "Profanity XMPP client"

.SH NAME
/mood

.SH DESCRIPTION
Set your mood (XEP-0107).

.SH SYNOPSIS
/mood on|off

.LP
/mood set <mood> [text]

.LP
/mood clear

.LP

.SH ARGUMENTS
.PP
\fBon|off\fR
.RS 4
Enable or disable displaying the mood of other users. On by default.
.RE
.PP
\fBset <mood> [text]\fR
.RS 4
Set user mood to <mood> with an optional [text]. Use /mood set <tab> to toggle through predefined moods.
.RE
.PP
\fBclear\fR
.RS 4
Clear your user mood.
.RE

.SH EXAMPLES
/mood set happy "So happy to use Profanity!"

.LP
/mood set amazed

.LP
/mood clear

.LP
