.TH man 1 "2025-03-27" "0.15.0" "Profanity XMPP client"

.SH NAME
/subject

.SH DESCRIPTION
Set, modify, or clear room subject.

.SH SYNOPSIS
/subject set <subject>

.LP
/subject edit <subject>

.LP
/subject editor

.LP
/subject prepend <text>

.LP
/subject append <text>

.LP
/subject clear

.LP

.SH ARGUMENTS
.PP
\fBset <subject>\fR
.RS 4
Set the room subject.
.RE
.PP
\fBedit <subject>\fR
.RS 4
Edit the current room subject, tab autocompletion will display the subject to edit.
.RE
.PP
\fBeditor\fR
.RS 4
Edit the current room subject in external editor.
.RE
.PP
\fBprepend <text>\fR
.RS 4
Prepend text to the current room subject, use double quotes if a trailing space is needed.
.RE
.PP
\fBappend <text>\fR
.RS 4
Append text to the current room subject, use double quotes if a preceding space is needed.
.RE
.PP
\fBclear\fR
.RS 4
Clear the room subject.
.RE
