.TH man 1 "2021-01-09" "0.10.0" "Profanity XMPP client"

.SH NAME
/theme

.SH DESCRIPTION
Load a theme, includes colours and UI options.

.SH SYNOPSIS
/theme list

.LP
/theme load <theme>

.LP
/theme full-load <theme>

.LP
/theme colours

.LP
/theme properties

.LP

.SH ARGUMENTS
.PP
\fBlist\fR
.RS 4
List all available themes.
.RE
.PP
\fBload <theme>\fR
.RS 4
Load colours from specified theme. 'default' will reset to the default theme.
.RE
.PP
\fBfull-load <theme>\fR
.RS 4
Same as 'load' but will also load preferences set in the theme, not just colours.
.RE
.PP
\fBcolours\fR
.RS 4
Show colour values as rendered by the terminal.
.RE
.PP
\fBproperties\fR
.RS 4
Show colour settings for current theme.
.RE

.SH EXAMPLES
/theme list

.LP
/theme load forest

.LP
