.TH man 1 "2021-07-14" "0.10.0" "Profanity XMPP client"

.SH NAME
/ox

.SH DESCRIPTION
OpenPGP (OX) commands to manage keys, and perform OpenPGP encryption during chat sessions. Your OpenPGP key needs a user-id with your JID URI (xmpp:local@domain.tld). A key can be generated with "gpg --quick-gen-key xmpp:local@domain.tld future-default default 3y".

.SH SYNOPSIS
/ox keys

.LP
/ox contacts

.LP
/ox start [<contact>]

.LP
/ox end

.LP
/ox log on|off|redact

.LP
/ox char <char>

.LP
/ox sendfile on|off

.LP
/ox announce <file>

.LP
/ox discover <jid>

.LP
/ox request <jid> <keyid>

.LP

.SH ARGUMENTS
.PP
\fBkeys\fR
.RS 4
List all keys known to the system.
.RE
.PP
\fBcontacts\fR
.RS 4
Show contacts with assigned public keys.
.RE
.PP
\fBstart [<contact>]\fR
.RS 4
Start PGP encrypted chat, current contact will be used if not specified.
.RE
.PP
\fBend\fR
.RS 4
End PGP encrypted chat with the current recipient.
.RE
.PP
\fBlog on|off\fR
.RS 4
Enable or disable plaintext logging of PGP encrypted messages.
.RE
.PP
\fBlog redact\fR
.RS 4
Log PGP encrypted messages, but replace the contents with [redacted]. This is the default.
.RE
.PP
\fBchar <char>\fR
.RS 4
Set the character to be displayed next to PGP encrypted messages.
.RE
.PP
\fBannounce <file>\fR
.RS 4
Announce a public key by pushing it on the XMPP Server
.RE
.PP
\fBdiscover <jid>\fR
.RS 4
Discover public keys of a jid. The OpenPGP Key IDs will be displayed
.RE
.PP
\fBrequest <jid>\fR
.RS 4
Request public keys
.RE
.PP
\fBsendfile on|off\fR
.RS 4
Allow /sendfile to send unencrypted files while otherwise using PGP.
.RE

.SH EXAMPLES
/ox log off

.LP
/ox start odin@valhalla.edda

.LP
/ox end

.LP
/ox char X

.LP
