.TH man 1 "2025-03-27" "0.15.0" "Profanity XMPP client"

.SH NAME
/priority

.SH DESCRIPTION
Set priority for the current account. See the /account command for specific priority settings per presence status.

.SH SYNOPSIS
/priority <priority>

.LP

.SH ARGUMENTS
.PP
\fB<priority>\fR
.RS 4
Number between -128 and 127, default: 0.
.RE
