.TH man 1 "2022-04-04" "0.12.0" "Profanity XMPP client"

.SH NAME
/register

.SH DESCRIPTION
Register an account on a server.

.SH SYNOPSIS
/register <username> <server> [port <port>] [tls force|allow|trust|legacy|disable]

.LP

.SH ARGUMENTS
.PP
\fB<username>\fR
.RS 4
Username to register with.
.RE
.PP
\fB<server>\fR
.RS 4
Server to register account on.
.RE
.PP
\fBport <port>\fR
.RS 4
The port to use if different to the default (5222, or 5223 for SSL).
.RE
.PP
\fBtls force\fR
.RS 4
Force TLS connection, and fail if one cannot be established. This is the default behavior.
.RE
.PP
\fBtls allow\fR
.RS 4
Use TLS for the connection if it is available.
.RE
.PP
\fBtls trust\fR
.RS 4
Force TLS connection and trust the server's certificate.
.RE
.PP
\fBtls legacy\fR
.RS 4
Use legacy TLS for the connection. This forces TLS just after the TCP connection is established. Use when a server doesn't support STARTTLS.
.RE
.PP
\fBtls disable\fR
.RS 4
Disable TLS for the connection.
.RE

.SH EXAMPLES
/register odin valhalla.edda 

.LP
/register freyr vanaheimr.edda port 5678

.LP
/register me 127.0.0.1 tls disable

.LP
/register someuser my.xmppserv.er port 5443 tls force

.LP
