.TH man 1 "2022-09-13" "0.13.0" "Profanity XMPP client"

.SH NAME
/export

.SH DESCRIPTION
Exports contacts to a csv file.

.SH SYNOPSIS
/export <filepath>

.LP

.SH ARGUMENTS
.PP
\fB<filepath>\fR
.RS 4
Path to the output file.
.RE

.SH EXAMPLES
/export /path/to/output.csv

.LP
/export ~/contacts.csv

.LP
