.TH man 1 "2023-08-03" "0.13.1" "Profanity XMPP client"

.SH NAME
/stamp

.SH DESCRIPTION
Set chat window stamp. The format of line in the chat window is: "<timestamp> <encryption sign> <stamp> <message>" where <stamp> is "me:" for incoming messages or "username@server/resource" for outgoing messages. This command allows to change <stamp> value.

.SH SYNOPSIS
/stamp outgoing <string>

.LP
/stamp incoming <string>

.LP
/stamp unset outgoing|incoming

.LP

.SH ARGUMENTS
.PP
\fBoutgoing\fR
.RS 4
Set outgoing stamp
.RE
.PP
\fBincoming\fR
.RS 4
Set incoming stamp
.RE
.PP
\fBunset outgoing|incoming\fR
.RS 4
Use the defaults
.RE

.SH EXAMPLES
/stamp outgoing -->

.LP
/stamp incoming <--

.LP
/stamp unset incoming

.LP
