.TH man 1 "2026-02-23" "0.16.0" "Profanity XMPP client"

.SH NAME
/mam

.SH DESCRIPTION
Enable/Disable Message Archive Management (XEP-0313) Currently MAM in groupchats (MUCs) is not supported. Use the PG UP key to load more history.

.SH SYNOPSIS
/mam <on>|<off>

.LP

.SH ARGUMENTS
.PP
\fBon|off\fR
.RS 4
Enable or disable MAM
.RE
