.TH man 1 "2022-04-04" "0.12.0" "Profanity XMPP client"

.SH NAME
/sendfile

.SH DESCRIPTION
Send a file using XEP-0363 HTTP file transfer.

.SH SYNOPSIS
/sendfile <file>

.LP

.SH ARGUMENTS
.PP
\fB<file>\fR
.RS 4
Path to the file.
.RE

.SH EXAMPLES
/sendfile /etc/hosts

.LP
/sendfile ~/images/sweet_cat.jpg

.LP
