.TH man 1 "2023-08-03" "0.13.1" "Profanity XMPP client"

.SH NAME
/privacy

.SH DESCRIPTION
Configure privacy settings.Also check the the following settings in /account: clientid to set the client identification namesession_alarm to configure an alarm when more clients log in.

.SH SYNOPSIS
/privacy logging on|redact|off

.LP
/privacy os on|off

.LP

.SH ARGUMENTS
.PP
\fBlogging on|redact|off\fR
.RS 4
Switch chat logging. This will also disable logging in the internally used SQL database. Your messages will not be saved anywhere locally. This might have unintended consequences, such as not being able to decrypt OMEMO encrypted messages received later via MAM, and should be used with caution.
.RE
.PP
\fBos on|off\fR
.RS 4
Choose whether to include the OS name if a user asks for software information (XEP-0092).
.RE

.SH EXAMPLES
/privacy logging off

.LP
/privacy os off

.LP
