.TH man 1 "2022-09-13" "0.13.0" "Profanity XMPP client"

.SH NAME
/slashguard

.SH DESCRIPTION
Slashguard won't accept a slash in the first 4 characters of your input field. It tries to protect you from typing ' /quit' and similar things in chats.

.SH SYNOPSIS
/slashguard on|off

.LP

.SH ARGUMENTS
.PP
\fBon|off\fR
.RS 4
Enable or disable slashguard.
.RE
