.TH man 1 "2021-09-28" "0.11.0" "Profanity XMPP client"

.SH NAME
/mam

.SH DESCRIPTION
Enable/Disable Message Archive Management (XEP-0313) MAM is in experimental state. For regular users there are still many confusing things when enabling this feature. We are going to work on this in future releases. So far this setting is mostly here for developers.

.SH SYNOPSIS
/mam <on>|<off>

.LP

.SH ARGUMENTS
.PP
\fBon|off\fR
.RS 4
Enable or disable MAM
.RE
