.TH man 1 "2021-01-09" "0.10.0" "Profanity XMPP client"

.SH NAME
/blocked

.SH DESCRIPTION
Manage blocked users (XEP-0191), calling with no arguments shows the current list of blocked users. To blog a certain user in a MUC use the following as jid: room@conference.example.org/spammy-user

.SH SYNOPSIS
/blocked

.LP
/blocked add [<jid>]

.LP
/blocked remove <jid>

.LP

.SH ARGUMENTS
.PP
\fBadd [<jid>]\fR
.RS 4
Block the specified Jabber ID. If in a chat window and no jid is specified, the current recipient will be blocked.
.RE
.PP
\fBremove <jid>\fR
.RS 4
Remove the specified Jabber ID from the blocked list.
.RE

.SH EXAMPLES
/blocked add hel@helheim.edda

.LP
/blocked add profanity@rooms.dismail.de/spammy-user

.LP
