.TH man 1 "2023-08-03" "0.13.1" "Profanity XMPP client"

.SH NAME
/log

.SH DESCRIPTION
Manage profanity log settings.

.SH SYNOPSIS
/log where

.LP
/log rotate on|off

.LP
/log maxsize <bytes>

.LP
/log shared on|off

.LP
/log level INFO|DEBUG|WARN|ERROR

.LP

.SH ARGUMENTS
.PP
\fBwhere\fR
.RS 4
Show the current log file location.
.RE
.PP
\fBrotate on|off\fR
.RS 4
Rotate log, default on. Does not take effect if you specified a filename yourself when starting Profanity.
.RE
.PP
\fBmaxsize <bytes>\fR
.RS 4
With rotate enabled, specifies the max log size, defaults to 10485760 (10MB).
.RE
.PP
\fBshared on|off\fR
.RS 4
Share logs between all instances, default: on. When off, the process id will be included in the log filename. Does not take effect if you specified a filename yourself when starting Profanity.
.RE
.PP
\fBlevel INFO|DEBUG|WARN|ERROR\fR
.RS 4
Set the log level. Default is INFO. Only works with default log file, not with user provided log file during startup via -f.
.RE
