.TH man 1 "2022-09-13" "0.13.0" "Profanity XMPP client"

.SH NAME
/history

.SH DESCRIPTION
Switch chat history on or off, /logging chat will automatically be enabled when this setting is on. When history is enabled, previous messages are shown in chat windows.

.SH SYNOPSIS
/history on|off

.LP

.SH ARGUMENTS
.PP
\fBon|off\fR
.RS 4
Enable or disable showing chat history.
.RE
