.TH man 1 "2023-08-03" "0.13.1" "Profanity XMPP client"

.SH NAME
/reconnect

.SH DESCRIPTION
Set the reconnect attempt interval for when the connection is lost or immediately trigger a reconnect.

.SH SYNOPSIS
/reconnect <seconds>

.LP
/reconnect now

.LP

.SH ARGUMENTS
.PP
\fB<seconds>\fR
.RS 4
Number of seconds before attempting to reconnect, a value of 0 disables reconnect.
.RE
.PP
\fBnow\fR
.RS 4
Immediately trigger a reconnect.
.RE
