.TH man 1 "2022-09-13" "0.13.0" "Profanity XMPP client"

.SH NAME
/correct

.SH DESCRIPTION
Correct and resend the last message (XEP-0308). Use tab completion to get the last sent message. For more information on how to configure corrections, see: /help correction.

.SH SYNOPSIS
/correct <message>

.LP

.SH ARGUMENTS
.PP
\fBmessage\fR
.RS 4
The corrected message.
.RE
