.TH man 1 "2022-09-13" "0.13.0" "Profanity XMPP client"

.SH NAME
/affiliation

.SH DESCRIPTION
Manage room affiliations. Affiliation may be one of owner, admin, member, outcast or none.

.SH SYNOPSIS
/affiliation set <affiliation> <jid> [<reason>]

.LP
/affiliation list [<affiliation>]

.LP
/affiliation request

.LP
/affiliation register

.LP

.SH ARGUMENTS
.PP
\fBset <affiliation> <jid> [<reason>]\fR
.RS 4
Set the affiliation of user with jid, with an optional reason.
.RE
.PP
\fBlist [<affiliation>]\fR
.RS 4
List all users with the specified affiliation, or all if none specified.
.RE
.PP
\fBrequest\fR
.RS 4
Request voice.
.RE
.PP
\fBregister\fR
.RS 4
Register your nickname with the MUC.
.RE
