.TH man 1 "2026-04-10" "0.18.0" "Profanity XMPP client"

.SH NAME
/spellcheck

.SH DESCRIPTION
Enable or disable spellchecking, or set the language.

.SH SYNOPSIS
/spellcheck on|off

.LP
/spellcheck list

.LP
/spellcheck lang <locale>

.LP

.SH ARGUMENTS
.PP
\fBon|off\fR
.RS 4
Enable or disable spellchecking.
.RE
.PP
\fBlist\fR
.RS 4
List available dictionaries recognized by Enchant.
.RE
.PP
\fBlang <locale>\fR
.RS 4
Set the spellcheck language (en_US).
.RE
