.TH man 1 "2022-04-04" "0.12.0" "Profanity XMPP client"

.SH NAME
/avatar

.SH DESCRIPTION
Download avatar (XEP-0084) for a certain contact. If nothing happens after using this command the user either doesn't have an avatar set at all or doesn't use XEP-0084 to publish it.

.SH SYNOPSIS
/avatar get <barejid>

.LP
/avatar open <barejid>

.LP

.SH ARGUMENTS
.PP
\fBget <barejid>\fR
.RS 4
Download the avatar. barejid is the JID to download avatar from.
.RE
.PP
\fBopen <barejid>\fR
.RS 4
Download avatar and open it with command.
.RE

.SH EXAMPLES
/avatar get thor@valhalla.edda

.LP
/avatar open freyja@vanaheimr.edda

.LP
