.TH man 1 "2022-04-04" "0.12.0" "Profanity XMPP client"

.SH NAME
/ping

.SH DESCRIPTION
Sends an IQ ping stanza to the specified JID. If no JID is supplied, your chat server will be pinged.

.SH SYNOPSIS
/ping [<jid>]

.LP

.SH ARGUMENTS
.PP
\fB<jid>\fR
.RS 4
The Jabber ID to send the ping request to.
.RE
