.TH man 1 "2022-03-30" "0.12.0" "Profanity XMPP client"

.SH NAME
/executable

.SH DESCRIPTION
Configure executable that should be called upon a certain command.

.SH SYNOPSIS
/executable avatar <cmd>

.LP
/executable urlopen set <cmdtemplate>

.LP
/executable urlopen default

.LP
/executable urlsave set <cmdtemplate>

.LP
/executable urlsave default

.LP

.SH ARGUMENTS
.PP
\fBavatar\fR
.RS 4
Set executable that is run by /avatar open. Use your favorite image viewer.
.RE
.PP
\fBurlopen set\fR
.RS 4
Set executable that is run by /url open. Takes a command template that replaces %u and %p with the URL and path respectively.
.RE
.PP
\fBurlopen default\fR
.RS 4
Restore to default settings.
.RE
.PP
\fBurlsave set\fR
.RS 4
Set executable that is run by /url save. Takes a command template that replaces %u and %p with the URL and path respectively.
.RE
.PP
\fBurlsave default\fR
.RS 4
Use the built-in download method for saving.
.RE
.PP
\fBeditor set\fR
.RS 4
Set editor to be used with /editor. Needs a terminal editor or a script to run a graphical editor.
.RE

.SH EXAMPLES
/executable avatar xdg-open

.LP
/executable urlopen set "xdg-open %u"

.LP
/executable urlopen set "firefox %u"

.LP
/executable urlopen default

.LP
/executable urlsave set "wget %u -O %p"

.LP
/executable urlsave set "curl %u -o %p"

.LP
/executable urlsave default

.LP
/executable editor set vim

.LP
