.TH man 1 "2025-08-22" "0.15.0" "Profanity XMPP client"

.SH NAME
/invite

.SH DESCRIPTION
Manage room invites. Send an invite to a contact for the current chat room. List received invites. Decline them using /invite decline and accept them using /join.

.SH SYNOPSIS
/invite send <contact> [<message>]

.LP
/invite list

.LP
/invite decline

.LP

.SH ARGUMENTS
.PP
\fBsend <contact> [<message>]\fR
.RS 4
The contact you wish to invite. And an optional message.
.RE
.PP
\fBlist\fR
.RS 4
Show all rooms that you have been invited to, and not accepted or declined.
.RE
.PP
\fBdecline <room>\fR
.RS 4
Decline a chat room invitation.
.RE

.SH EXAMPLES
/invite send gustavo@pollos.tx

.LP
/invite decline profanity@rooms.dismail.de

.LP
/invite list

.LP
