.TH man 1 "2021-01-09" "0.10.0" "Profanity XMPP client"

.SH NAME
/statusbar

.SH DESCRIPTION
Manage statusbar display preferences.

.SH SYNOPSIS
/statusbar show name|number|read

.LP
/statusbar hide name|number|read

.LP
/statusbar maxtabs <value>

.LP
/statusbar tablen <value>

.LP
/statusbar self user|barejid|fulljid|off

.LP
/statusbar chat user|jid

.LP
/statusbar room room|jid

.LP
/statusbar up

.LP
/statusbar down

.LP

.SH ARGUMENTS
.PP
\fBmaxtabs <value>\fR
.RS 4
Set the maximum number of tabs to display, <value> must be between 0 and 10.
.RE
.PP
\fBtablen <value>\fR
.RS 4
Set the maximum number of characters to show as the tab name, 0 sets to unlimited.
.RE
.PP
\fBshow|hide name\fR
.RS 4
Show or hide names in tabs.
.RE
.PP
\fBshow|hide number\fR
.RS 4
Show or hide numbers in tabs.
.RE
.PP
\fBshow|hide read\fR
.RS 4
Show or hide inactive tabs.
.RE
.PP
\fBself user|barejid|fulljid\fR
.RS 4
Show account user name, barejid, fulljid as status bar title.
.RE
.PP
\fBself off\fR
.RS 4
Disable showing self as status bar title.
.RE
.PP
\fBchat user|jid\fR
.RS 4
Show users name, or the fulljid if no nick is present for chat tabs.
.RE
.PP
\fBroom room|jid\fR
.RS 4
Show room name, or the fulljid for room tabs.
.RE
.PP
\fBup\fR
.RS 4
Move the status bar up the screen.
.RE
.PP
\fBdown\fR
.RS 4
Move the status bar down the screen.
.RE

.SH EXAMPLES
/statusbar maxtabs 8

.LP
/statusbar tablen 5

.LP
/statusbar self user

.LP
/statusbar chat jid

.LP
/statusbar hide read

.LP
/statusbar hide name

.LP
