.TH man 1 "2022-09-13" "0.13.0" "Profanity XMPP client"

.SH NAME
/caps

.SH DESCRIPTION
Find out a contacts, or room members client software capabilities. If in private chat initiated from a chat room, no parameter is required.

.SH SYNOPSIS
/caps

.LP
/caps <fulljid>|<nick>

.LP

.SH ARGUMENTS
.PP
\fB<fulljid>\fR
.RS 4
If in the console or a chat window, the full JID for which you wish to see capabilities.
.RE
.PP
\fB<nick>\fR
.RS 4
If in a chat room, nickname for which you wish to see capabilities.
.RE

.SH EXAMPLES
/caps ran@cold.sea.org/laptop

.LP
/caps ran@cold.sea.org/phone

.LP
/caps aegir

.LP
