.TH man 1 "2025-03-27" "0.15.0" "Profanity XMPP client"

.SH NAME
/url

.SH DESCRIPTION
Open or save URLs. This works with OMEMO encrypted files as well.

.SH SYNOPSIS
/url open <url>

.LP
/url save <url> [<path>]

.LP

.SH ARGUMENTS
.PP
\fBopen\fR
.RS 4
Open URL with predefined executable.
.RE
.PP
\fBsave\fR
.RS 4
Save URL to optional path. The location is displayed after successful download.
.RE

.SH EXAMPLES
/url open https://profanity-im.github.io

.LP
/url save https://profanity-im.github.io/guide/latest/userguide.html /home/user/Download/

.LP
