.TH man 1 "2022-09-13" "0.13.0" "Profanity XMPP client"

.SH NAME
/titlebar

.SH DESCRIPTION
Titlebar settings.

.SH SYNOPSIS
/titlebar up

.LP
/titlebar down

.LP
/titlebar show|hide [encwarn|resource|tls]

.LP

.SH ARGUMENTS
.PP
\fBup\fR
.RS 4
Move the title bar up the screen.
.RE
.PP
\fBdown\fR
.RS 4
Move the title bar down the screen.
.RE
.PP
\fBshow tls\fR
.RS 4
Show or hide TLS indicator in the titlebar.
.RE
.PP
\fBshow encwarn\fR
.RS 4
Enable or disable the unencrypted warning message in the titlebar.
.RE
.PP
\fBshow resource\fR
.RS 4
Show or hide the current resource in the titlebar.
.RE
.PP
\fBshow name\fR
.RS 4
In case of a MUC. Show the MUC name in the titlebar.
.RE
.PP
\fBshow jid\fR
.RS 4
In case of a MUC. Show the JID in the titlebar.
.RE

.SH EXAMPLES
/titlebar up

.LP
/titlebar show tls

.LP
/titlebar hide encwarn

.LP
