.TH man 1 "2021-09-28" "0.11.0" "Profanity XMPP client"

.SH NAME
/receipts

.SH DESCRIPTION
Enable or disable message delivery receipts. The interface will indicate when a message has been received.

.SH SYNOPSIS
/receipts request on|off

.LP
/receipts send on|off

.LP

.SH ARGUMENTS
.PP
\fBrequest on|off\fR
.RS 4
Whether or not to request a receipt upon sending a message.
.RE
.PP
\fBsend on|off\fR
.RS 4
Whether or not to send a receipt if one has been requested with a received message.
.RE
