.TH man 1 "2023-08-03" "0.13.1" "Profanity XMPP client"

.SH NAME
/correct-editor

.SH DESCRIPTION
Spawn external editor to correct and resend the last message (XEP-0308). For more information on how to configure corrections, see: /help correction. Use /executable to set your favourite editor.

.SH SYNOPSIS
/correct-editor

.LP
