.TH Profanity 1 "August 2012" "Profanity XMPP client"
.SH NAME
Profanity \- a simple console based XMPP chat client for Linux.
.SH SYNOPSIS
.B profanity
[-vhd] [-l level]
.SH DESCRIPTION
.B Profanity
is a simple lightweight console based XMPP chat client.  It's emphasis is 
on having a simple and configurable UI, see the homepage
at:
.br
.PP
<http://www.boothj5.com/profanity.shtml>
.SH OPTIONS
.TP
.BI "\-v, \-\-version"
Show version information.
.TP
.BI "\-h, \-\-help"
Show help on command line arguments.
.TP
.BI "\-d, \-\-disable-tls"
Disable TLS for servers that either don't support it, or claim to but do not
complete the handshake.
.TP
.BI "\-l, \-\-log="LEVEL
Set the logging level,
.I LEVEL
may be set to DEBUG, INFO (the default), WARN or ERROR.
.SH USING PROFANITY
The
.B Profanity 
user interface contains 3 main elements.
.PP
The title bar at the top, shows various information about who you are chatting
with, and your current status at the top right corner.
.PP
The status bar near the bottom, shows information about the user you are logged
in as, and shows which windows are currently active, at the bottom right corner
of the screen.
.PP
The input line, the last line, is where all user input goes, including commands
starting with the "/" character and messages.
.PP
The main window holds a console window where information is given, press F1 to
get back to the console window.  Up to 9 chat windows may be open at any one
time, to access them use the F2-F10 keys.  When in a chat window, you do not
need to use the "/msg" command.
.SH SEE ALSO
.B Profanity
itself has a lot of built\-in help. Check the /help command for more information.
Type "/help help" for information on how to use help itself.
.SH CONFIGURATION
Configuration for
.B Profanity
is stored in
.I ~/.profanity/config
, see the following example:
.br
.RS
.PP
[ui]
.br
beep=false
.br
flash=false 
.br
showsplash=false 
.br
notify=true 
.br
chlog=true 
.br
history=true 
.br
typing=true 
.br
remind=15 
.br
.PP
[colours]
.br
away=magenta
.br
chat=yellow
.br
xa=blue
.br
online=white
.br
dnd=red
.br
offline=cyan
.br
bkgnd=default
.br
text=white
.br
err=red
.br
inc=yellow
.br
bar=green
.br
bar_draw=black
.br
bar_text=black
.PP
[connections]
.br
logins=user1@server1.org;myuser@server2.com;
.PP
.RE
The [ui] section contains basic preferences, you can find more help on these
settings by typing "/help beep" for example in Profanity.
.PP
The [colours] section allows you to tailor the colours used in Profanity to
suit your terminal preferences.  Available colours are black, white, red, 
green, blue, yellow, cyan, magenta and default, where default is the default
forground or background colour on your terminal.
.PP
The [connections] section is the list of users that will appear in tab
completion for the /connect command.  This list is automatically populated
when you successfully log in as a user.
.SH BUGS
Bugs can either be reported by sending a mail directly to:
.br
.PP
<boothj5web@gmail.com>
.br
.PP
or to the mailing list at:
.br
.PP
<https://groups.google.com/forum/#!forum/profanitydev>
.br
.PP
or with a Github account by logging issues on the issue tracker at:
.br
.PP
<https://github.com/boothj5/profanity>
.SH LICENSE
Copyright (C) 2012 James Booth <boothj5web@gmail.com>.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
.SH AUTHORS/CREDITS
.B Profanity
was written by James Booth
.B <boothj5web@gmail.com>
with contributions from:
.br
.PP
Dolan O'Toole
.br
Colin Bradley
.br
Dmitry Podgorny <pasis.ua@gmail.com>
