.TH man 1 "2021-01-09" "0.10.0" "Profanity XMPP client"

.SH NAME
/log

.SH DESCRIPTION
Manage profanity log settings.

.SH SYNOPSIS
/log where

.LP
/log rotate on|off

.LP
/log maxsize <bytes>

.LP
/log shared on|off

.LP

.SH ARGUMENTS
.PP
\fBwhere\fR
.RS 4
Show the current log file location.
.RE
.PP
\fBrotate on|off\fR
.RS 4
Rotate log, default on. Does not take effect if you specified a filename yourself when starting Profanity.
.RE
.PP
\fBmaxsize <bytes>\fR
.RS 4
With rotate enabled, specifies the max log size, defaults to 1048580 (1MB).
.RE
.PP
\fBshared on|off\fR
.RS 4
Share logs between all instances, default: on. When off, the process id will be included in the log filename. Does not take effect if you specified a filename yourself when starting Profanity.
.RE
