.TH man 1 "2025-08-22" "0.15.0" "Profanity XMPP client"

.SH NAME
/close

.SH DESCRIPTION
Close windows. Passing no argument closes the current window.

.SH SYNOPSIS
/close

.LP
/close <num>

.LP
/close <barejid>

.LP
/close <nick>

.LP
/close <roomjid>

.LP
/close <roomoccupantjid>

.LP
/close xmlconsole

.LP
/close all|read

.LP

.SH ARGUMENTS
.PP
\fB<num>\fR
.RS 4
Close specified window number.
.RE
.PP
\fB<barejid>\fR
.RS 4
Close chat window with contact by JID if open.
.RE
.PP
\fB<nick>\fR
.RS 4
Close chat window with contact by nickname if open.
.RE
.PP
\fB<roomjid>\fR
.RS 4
Close chat room window with roomjid if open.
.RE
.PP
\fB<roomoccupantjid>\fR
.RS 4
Close private chat roomoccupantjid if open.
.RE
.PP
\fBxmlconsole\fR
.RS 4
Close the XML Console window if open.
.RE
.PP
\fBall\fR
.RS 4
Close all windows.
.RE
.PP
\fBread\fR
.RS 4
Close all windows that have no unread messages.
.RE
