.TH man 1 "2022-04-04" "0.12.0" "Profanity XMPP client"

.SH NAME
/info

.SH DESCRIPTION
Show information about a contact, room, or room member. Passing no argument in a chat window will use the current recipient. Passing no argument in a chat room will display information about the room.

.SH SYNOPSIS
/info

.LP
/info <contact>|<nick>

.LP

.SH ARGUMENTS
.PP
\fB<contact>\fR
.RS 4
The contact you wish to view information about.
.RE
.PP
\fB<nick>\fR
.RS 4
When in a chat room, the occupant you wish to view information about.
.RE

.SH EXAMPLES
/info thor@aasgard.server.org

.LP
/info heimdall

.LP
