.TH man 1 "2021-01-09" "0.10.0" "Profanity XMPP client"

.SH NAME
/form

.SH DESCRIPTION
Form configuration.

.SH SYNOPSIS
/form show

.LP
/form submit

.LP
/form cancel

.LP
/form help [<tag>]

.LP

.SH ARGUMENTS
.PP
\fBshow\fR
.RS 4
Show the current form.
.RE
.PP
\fBsubmit\fR
.RS 4
Submit the current form.
.RE
.PP
\fBcancel\fR
.RS 4
Cancel changes to the current form.
.RE
.PP
\fBhelp [<tag>]\fR
.RS 4
Display help for form, or a specific field.
.RE
