.TH man 1 "2022-03-30" "0.12.0" "Profanity XMPP client"

.SH NAME
/mood

.SH DESCRIPTION
Set your mood (XEP-0107).

.SH SYNOPSIS
/mood set <mood> [text]

.LP
/mood clear

.LP

.SH ARGUMENTS
.PP
\fBset <mood> <\fR
.RS 4
Set user mood to <mood> with an optional [text]. Use /mood set <tab> to toggle through predfined moods.
.RE
.PP
\fBclear\fR
.RS 4
Clear your user mood.
.RE

.SH EXAMPLES
/mood set happy "So happy to use Profanity!"

.LP
/mood set amazed

.LP
/mood clear

.LP
