.TH man 1 "2022-04-04" "0.12.0" "Profanity XMPP client"

.SH NAME
/autoconnect

.SH DESCRIPTION
Enable or disable autoconnect on start up. The setting can be overridden by the -a (--account) command line option.

.SH SYNOPSIS
/autoconnect set <account>

.LP
/autoconnect off

.LP

.SH ARGUMENTS
.PP
\fBset <account>\fR
.RS 4
Connect with account on start up.
.RE
.PP
\fBoff\fR
.RS 4
Disable autoconnect.
.RE

.SH EXAMPLES
/autoconnect set ulfhednar@valhalla.edda

.LP
/autoconnect off

.LP
