.TH Profanity 1 "March 2014" "Profanity XMPP client"
.SH NAME
Profanity \- a simple console based XMPP chat client.
.SH SYNOPSIS
.B profanity
[-vhd] [-l level]
.SH DESCRIPTION
.B Profanity
is a simple lightweight console based XMPP chat client.  It's emphasis is 
on having a simple and configurable command driven UI, see the homepage
at:
.br
.PP
<http://www.profanity.im>
.SH OPTIONS
.TP
.BI "\-v, \-\-version"
Show version information.
.TP
.BI "\-h, \-\-help"
Show help on command line arguments.
.TP
.BI "\-d, \-\-disable-tls"
Disable TLS for servers that either don't support it, or claim to but do not
complete the handshake.
.TP
.BI "\-l, \-\-log="LEVEL
Set the logging level,
.I LEVEL
may be set to DEBUG, INFO (the default), WARN or ERROR.
.SH USING PROFANITY
The user guide can be found at <http://www.profanity.im/userguide.html>.
.SH SEE ALSO
.B Profanity
itself has a lot of built\-in help. Check the /help command for more information.
Type "/help help" for information on how to use help itself.
.SH CONFIGURATION
Configuration for
.B Profanity
is stored in
.I $XDG_CONFIG_HOME/profanity/profrc
, details on configuring Profanity can be found at <http://www.profanity.im/configuration.html>.
.PP
.SH BUGS
Bugs can either be reported by sending a mail directly to:
.br
.PP
<boothj5web@gmail.com>
.br
.PP
or to the mailing list at:
.br
.PP
<https://groups.google.com/forum/#!forum/profanitydev>
.br
.PP
or with a Github account by logging issues on the issue tracker at:
.br
.PP
<https://github.com/boothj5/profanity>
.SH LICENSE
Copyright (C) 2012 - 2014 James Booth <boothj5web@gmail.com>.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
.SH AUTHORS/CREDITS
.B Profanity
was written by James Booth
.B <boothj5web@gmail.com>
with many contributions from others, see the full list at: <https://github.com/boothj5/profanity/graphs/contributors>
