.TH man 1 "2022-04-04" "0.12.0" "Profanity XMPP client"

.SH NAME
/prefs

.SH DESCRIPTION
Show preferences for different areas of functionality. Passing no arguments shows all preferences.

.SH SYNOPSIS
/prefs [ui|desktop|chat|log|conn|presence|otr|pgp|omemo]

.LP

.SH ARGUMENTS
.PP
\fBui\fR
.RS 4
User interface preferences.
.RE
.PP
\fBdesktop\fR
.RS 4
Desktop notification preferences.
.RE
.PP
\fBchat\fR
.RS 4
Chat state preferences.
.RE
.PP
\fBlog\fR
.RS 4
Logging preferences.
.RE
.PP
\fBconn\fR
.RS 4
Connection handling preferences.
.RE
.PP
\fBpresence\fR
.RS 4
Chat presence preferences.
.RE
.PP
\fBotr\fR
.RS 4
Off The Record preferences.
.RE
.PP
\fBpgp\fR
.RS 4
OpenPGP preferences.
.RE
.PP
\fBomemo\fR
.RS 4
OMEMO preferences.
.RE
