.TH man 1 "2025-03-27" "0.15.0" "Profanity XMPP client"

.SH NAME
/flash

.SH DESCRIPTION
Make the terminal flash when incoming messages are received in another window. If the terminal doesn't support flashing, it may attempt to beep.

.SH SYNOPSIS
/flash on|off

.LP

.SH ARGUMENTS
.PP
\fBon|off\fR
.RS 4
Enable or disable terminal flash.
.RE
