.TH man 1 "2021-09-28" "0.11.0" "Profanity XMPP client"

.SH NAME
/script

.SH DESCRIPTION
Run command scripts. Scripts are stored in $XDG_DATA_HOME/profanity/scripts/ which is usually $HOME/.local/share/profanity/scripts/.

.SH SYNOPSIS
/script run <script>

.LP
/script list

.LP
/script show <script>

.LP

.SH ARGUMENTS
.PP
\fBscript run <script>\fR
.RS 4
Execute a script.
.RE
.PP
\fBscript list\fR
.RS 4
List all scripts TODO.
.RE
.PP
\fBscript show <script>\fR
.RS 4
Show the commands in script TODO.
.RE

.SH EXAMPLES
/script list

.LP
/script run myscript

.LP
/script show somescript

.LP
