.TH man 1 "2022-04-04" "0.12.0" "Profanity XMPP client"

.SH NAME
/logging

.SH DESCRIPTION
Configure chat logging. Switch logging on or off. Chat logging will be enabled if /history is set to on. When disabling this option, /history will also be disabled. 

.SH SYNOPSIS
/logging chat|group on|off

.LP

.SH ARGUMENTS
.PP
\fBchat on|off\fR
.RS 4
Enable/Disable regular chat logging.
.RE
.PP
\fBgroup on|off\fR
.RS 4
Enable/Disable groupchat (room) logging.
.RE

.SH EXAMPLES
/logging chat on

.LP
/logging group off

.LP
