.TH man 1 "2023-08-03" "0.13.1" "Profanity XMPP client"

.SH NAME
/autoping

.SH DESCRIPTION
Set the interval between sending ping requests to the server to ensure the connection is kept alive.

.SH SYNOPSIS
/autoping set <seconds>

.LP
/autoping timeout <seconds>

.LP

.SH ARGUMENTS
.PP
\fBset <seconds>\fR
.RS 4
Number of seconds between sending pings, a value of 0 disables autoping.
.RE
.PP
\fBtimeout <seconds>\fR
.RS 4
Seconds to wait for autoping responses, after which the connection is considered broken.
.RE
