.TH man 1 "2022-04-04" "0.12.0" "Profanity XMPP client"

.SH NAME
/tray

.SH DESCRIPTION
Display an icon in the tray that will indicate new messages.

.SH SYNOPSIS
/tray on|off

.LP
/tray read on|off

.LP
/tray timer <seconds>

.LP

.SH ARGUMENTS
.PP
\fBon|off\fR
.RS 4
Show tray icon.
.RE
.PP
\fBread on|off\fR
.RS 4
Show tray icon when no unread messages.
.RE
.PP
\fBtimer <seconds>\fR
.RS 4
Set tray icon timer, seconds must be between 1-10.
.RE
