.TH man 1 "2022-03-30" "0.12.0" "Profanity XMPP client"

.SH NAME
/sub

.SH DESCRIPTION
Manage subscriptions to contact presence. If jid is omitted, the contact of the current window is used.

.SH SYNOPSIS
/sub request [<jid>]

.LP
/sub allow [<jid>]

.LP
/sub deny [<jid>]

.LP
/sub show [<jid>]

.LP
/sub sent

.LP
/sub received

.LP

.SH ARGUMENTS
.PP
\fBrequest [<jid>]\fR
.RS 4
Send a subscription request to the user.
.RE
.PP
\fBallow [<jid>]\fR
.RS 4
Approve a contact's subscription request.
.RE
.PP
\fBdeny [<jid>]\fR
.RS 4
Remove subscription for a contact, or deny a request.
.RE
.PP
\fBshow [<jid>]\fR
.RS 4
Show subscription status for a contact.
.RE
.PP
\fBsent\fR
.RS 4
Show all sent subscription requests pending a response.
.RE
.PP
\fBreceived\fR
.RS 4
Show all received subscription requests awaiting your response.
.RE

.SH EXAMPLES
/sub request odin@valhalla.edda

.LP
/sub allow odin@valhalla.edda

.LP
/sub request

.LP
/sub sent

.LP
