.TH man 1 "2021-07-14" "0.10.0" "Profanity XMPP client"

.SH NAME
/clear

.SH DESCRIPTION
Clear the current window. If you set persist_history you can still access the history by pressing PAGE UP.

.SH SYNOPSIS
/clear

.LP
/clear persist_history <on|off>

.LP

.SH ARGUMENTS
.PP
\fBpersist_history on|off\fR
.RS 4
Whether or not to clear the screen persistently.
.RE

.SH EXAMPLES
/clear

.LP
/clear persist_history

.LP
/clear persist_history on

.LP
