.TH man 1 "2021-01-09" "0.10.0" "Profanity XMPP client"

.SH NAME
/rooms

.SH DESCRIPTION
List the chat rooms available at the specified conference service. If no argument is supplied, the account preference 'muc.service' is used, 'conference.<domain-part>' by default. The filter argument only shows rooms that contain the provided text, case insensitive.

.SH SYNOPSIS
/rooms

.LP
/rooms filter <text>

.LP
/rooms service <service>

.LP
/rooms service <service> filter <text>

.LP
/rooms cache on|off|clear

.LP

.SH ARGUMENTS
.PP
\fBservice <service>\fR
.RS 4
The conference service to query.
.RE
.PP
\fBfilter <text>\fR
.RS 4
The text to filter results by.
.RE
.PP
\fBcache on|off\fR
.RS 4
Enable or disable caching of rooms list response, enabled by default.
.RE
.PP
\fBcache clear\fR
.RS 4
Clear the rooms response cache if enabled.
.RE

.SH EXAMPLES
/rooms

.LP
/rooms filter development

.LP
/rooms service conference.jabber.org

.LP
/rooms service conference.jabber.org filter "News Room"

.LP
