.TH man 1 "2023-08-03" "0.13.1" "Profanity XMPP client"

.SH NAME
/inputwin

.SH DESCRIPTION
Move the input window.

.SH SYNOPSIS
/inputwin up

.LP
/inputwin down

.LP

.SH ARGUMENTS
.PP
\fBup\fR
.RS 4
Move the input window up the screen.
.RE
.PP
\fBdown\fR
.RS 4
Move the input window down the screen.
.RE
