.TH man 1 "2022-09-13" "0.13.0" "Profanity XMPP client"

.SH NAME
/carbons

.SH DESCRIPTION
Enable or disable message carbons. Message carbons ensure that both sides of all conversations are shared with all the user's clients that implement this protocol.

.SH SYNOPSIS
/carbons on|off

.LP

.SH ARGUMENTS
.PP
\fBon|off\fR
.RS 4
Enable or disable message carbons.
.RE
