.TH man 1 "2023-08-03" "0.13.1" "Profanity XMPP client"

.SH NAME
/wintitle

.SH DESCRIPTION
Allow Profanity to modify the window title bar.

.SH SYNOPSIS
/wintitle show on|off

.LP
/wintitle goodbye on|off

.LP

.SH ARGUMENTS
.PP
\fBshow on|off\fR
.RS 4
Show current logged in user, and unread messages as the window title.
.RE
.PP
\fBgoodbye on|off\fR
.RS 4
Show a message in the title when exiting profanity.
.RE
