.TH man 1 "2026-02-23" "0.16.0" "Profanity XMPP client"

.SH NAME
/console

.SH DESCRIPTION
Configure what is displayed in the console window when messages are received. The default is set to 'all' for all types of messages.

.SH SYNOPSIS
/console chat all|first|none

.LP
/console muc all|first|mention|none

.LP
/console private all|first|none

.LP

.SH ARGUMENTS
.PP
\fBchat all\fR
.RS 4
Indicate all new chat messages in the console.
.RE
.PP
\fBchat first\fR
.RS 4
Indicate only the first new message per chat in the console.
.RE
.PP
\fBchat none\fR
.RS 4
Do not show any new chat messages in the console window.
.RE
.PP
\fBmuc all\fR
.RS 4
Indicate all new chat room messages in the console.
.RE
.PP
\fBmuc first\fR
.RS 4
Indicate only the first new message in each room in the console.
.RE
.PP
\fBmuc mention\fR
.RS 4
Indicate only messages in which you have been mentioned in the console.
.RE
.PP
\fBmuc none\fR
.RS 4
Do not show any new chat room messages in the console window.
.RE
.PP
\fBprivate all\fR
.RS 4
Indicate all new private room messages in the console.
.RE
.PP
\fBprivate first\fR
.RS 4
Indicate only the first private room message in the console.
.RE
.PP
\fBprivate none\fR
.RS 4
Do not show any new private room messages in the console window.
.RE
